version: '3.8'
services:

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    ports:
      - "27017:27017"
    networks:
      - mynet

  localstack:
    build: .
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "8055:8080"
    volumes:
      - ./tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynet


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - mynet

  kafka:
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - mynet

  app:
    build: .
    container_name: app
    depends_on:
      - mongodb
      - kafka
    ports:
      - 8082:8082
    networks:
    - mynet

networks:
  mynet:
    driver: bridge